# Generated by Django 3.0.7 on 2021-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('website', models.URLField(max_length=500)),
                ('symbol_name', models.CharField(max_length=100)),
                ('slugfield', models.SlugField(max_length=700)),
                ('market_Cap', models.PositiveIntegerField()),
                ('currencylength', models.CharField(choices=[('1', 'MILLION'), ('2', 'BILLION'), ('3', 'TRILLION')], max_length=1000)),
                ('Price', models.DecimalField(decimal_places=5, max_digits=1000000000000000)),
                ('circulating_Supply', models.DecimalField(decimal_places=5, max_digits=1000000000000000)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
