# Generated by Django 3.2.2 on 2021-05-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210530_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uuid',
            new_name='id',
        ),
    ]
